spring.datasource.url=jdbc:postgresql://localhost:5432/eventapi?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate=DEBUG
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.data.web.pageable.max-page-size=50
spring.data.web.pageable.default-page-size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.format_sql=true
org.hibernate.envers.audit_strategy=org.hibernate.envers.strategy.ValidityAuditStrategy
org.hibernate.envers.store_data_at_delete=true